id: A7771CEC5
title: 'A River Filled with the Amṛta of Love: A Liturgy for Saving and Releasing
  the Lives of Animals'
type: translation
pechas:
- I8E2419AF
- I9BDCD437
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:01:56.430764
  last_modified_at: 2023-01-04 13:01:56.430780
  collections:
  - Metrul Tendzin Gyatso Series
  - Works of Tibetan Masters
alignment_to_base:
  I8E2419AF/7D1C: D1DE
  I9BDCD437/2E9B: D1DE
